### ISSUE TITLE
gage chopping daemon returns same data many times before measurement_id updates

### ISSUE THREAD

**Issue by kameyer226** [yaq-project/yaqd-gage#13]
The YEP 310 is in draft but the measurement_id for the chopping acquisition does not update each time `get_measured` is called, instead returning the same data multiple times.   The number of time it returns the same data scales proportionally to the `segment_count`.

**Comment by ksunden** [comment]
this is expected behavior

get measured returns the latest measurment, only `measure` causes a new measurement to occur

It returns the same data as long as it is the most recent measurment, which explains the scaling, as it takes longer to take a new measurment the higher segment count is.

To ensure uniqueness, you should look at `measurement_id`

YEP 310 is in draft only because we have not taken the time to revise some wordings, conceptually it is in use already.

**Comment by ksunden** [comment]
measurement id is updated each time a new measurement is actually taken (either by calling `measure` or by the looping functionality of the `measure` command or by recieving an updated measurement some other way in the case of non-triggered sensors.

It is explicitly not updated by retrieving the measurement as in `get_measured`

**Comment by untzag** [comment]
@kameyer226 in what context were you surprised by this behavior? While @ksunden is exactly correct---this sounds like correct behavior for the daemon---perhaps you were interacting with some client or orchestration code that didn't work as expected. Would be happy to think through it further with you.

**Comment by kameyer226** [comment]
It is busy right now but I thought I did a measure command in there, I will check on that later thanks

**Comment by untzag** [comment]
Just anticipating a potential source of confusion---if you call `measure` DURING an ongoing measurement, it will not start a new measurement.

**Comment by kameyer226** [comment]
Can you confirm this is congruent with the 3rd paragraph of the YEP 310 proposal?

**Comment by untzag** [comment]
> This trait defines the concept of a "measurement_id". This is an integer that should increase every time the measure message is called. get_measured returns this measurement_id as a channel.

I see the confusion, that definitely could be clearer. `measurement_id` increments every time a measurement completes, not every time `measure` is called.

Thanks so much @kameyer226. I will make updating this language my top priority.
